---
linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:

files:
    ignore:
         'src/generated/*'
         'webroot/bower_components/*'
linters:   #Configured linters 
    fixers:      
        enable: true
